cmd: "g++"
name: "Build: C"
args:
  - "{FILE_ACTIVE} -o {FILE_ACTIVE_BASE}"
  - "&& open -a Terminal.app {FILE_ACTIVE_PATH}/./{FILE_ACTIVE_NAME_BASE}"
sh: true,
cwd: {FILE_ACTIVE_PATH}
# env:
#   VARIABLE1: "VALUE1"
#   VARIABLE2: "VALUE2"
# errorMatch:
#   - ^regexp1$
#   - ^regexp2$
# warningMatch:
#   - ^regexp1$
#   - ^regexp2$
# keymap: <keymap string>
atomCommandName: "Build: C"
targets:
  "Build: C Run":
      name: "Build: C Run"
      cmd: "g++"
      args:
        - "{FILE_ACTIVE} -o {FILE_ACTIVE_BASE}"
        - "&& {FILE_ACTIVE_PATH}/./{FILE_ACTIVE_NAME_BASE}"
  "Build: C Debug":
      name: "Build: C Debug"
      cmd: "g++"
      args:
        - "{FILE_ACTIVE} -g -o {FILE_ACTIVE_BASE}"
